---------------------------------------------------
--REWARD 리워드
---------------------------------------------------

DROP TABLE REWARD CASCADE CONSTRAINTS;

CREATE TABLE REWARD
(
    NO NUMBER PRIMARY KEY,
    PROJECT_NO NUMBER NOT NULL,
    "OPTION" VARCHAR2(20) NOT NULL,
    DETAIL VARCHAR2(200) NOT NULL,
    PRICE NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL
);

--프로젝트 번호 외래키 지정 (리워드)
ALTER TABLE REWARD ADD CONSTRAINT REWARD_PROJECT_REF_NO 
FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT;

--첨부파일 번호 시퀀스
DROP SEQUENCE SEQ_REWARD_NO;
CREATE SEQUENCE SEQ_REWARD_NO NOCACHE NOCYCLE;