---------------------------------------------------
--쿠폰 테이블
---------------------------------------------------
DROP TABLE COUPON CASCADE CONSTRAINTS;

CREATE TABLE COUPON
(
    NO NUMBER PRIMARY KEY,
    MEM_NO NUMBER NOT NULL,
    NAME VARCHAR2(400) NOT NULL,
    DISCOUNT NUMBER NOT NULL
);

--회원번호 외래키 지정 (쿠폰)
ALTER TABLE COUPON ADD CONSTRAINT MEM_NO 
FOREIGN KEY(NO) REFERENCES MEMBER;

--쿠폰번호 시퀀스
DROP SEQUENCE SEQ_COUPON_NO;
CREATE SEQUENCE SEQ_COUPON_NO NOCACHE NOCYCLE;

--쿠폰 더미데이터
INSERT INTO COUPON(NO,MEM_NO,NAME,DISCOUNT)VALUES(SEQ_COUPON_NO.NEXTVAL, 1,'생일쿠폰','3000');
INSERT INTO COUPON(NO,MEM_NO,NAME,DISCOUNT)VALUES(SEQ_COUPON_NO.NEXTVAL, 1,'신규쿠폰','1000');
INSERT INTO COUPON(NO,MEM_NO,NAME,DISCOUNT)VALUES(SEQ_COUPON_NO.NEXTVAL, 1,'깜작쿠폰','7000');
SELECT* FROM COUPON;

COMMIT;



-----------------------
--TEST
-----------------------

SELECT * FROM COUPON WHERE MEM_NO = ?
;