---------------------------------------------------
--PROJECT 프로젝트
---------------------------------------------------

DROP TABLE PROJECT CASCADE CONSTRAINTS;

CREATE TABLE PROJECT
(
    PROJECT_NO NUMBER PRIMARY KEY,
    CATEGORY_NO NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    REGISTER_DATE TIMESTAMP DEFAULT SYSDATE,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    GOAL NUMBER NOT NULL,
    MAKER_NO NUMBER NOT NULL,
    TEXT VARCHAR2(1000) NOT NULL,
    ACCOUNT_NO VARCHAR2(20) NOT NULL,
    SHIPPING_DATE DATE NOT NULL,
    THUMBNAIL_NAME VARCHAR2(255) NOT NULL,
    THUMBNAIL_PATH VARCHAR2(500) NOT NULL,
    ETC VARCHAR2(1000),
    ACCOUNT_BANK VARCHAR2(20) NOT NULL,
    ACCOUNT_NAME VARCHAR2(20) NOT NULL,
    MAKER_INFO VARCHAR2(500),
    STATUS CHAR(1) DEFAULT 'R' CHECK(STATUS IN('R','N','A','B','I','S','F','D'))
);

--프로젝트 상태 코멘트
COMMENT ON COLUMN PROJECT.STATUS IS 'R=접수, N=반려, A=검토중, B=진행전, I=진행중, S=마감(성공), F=마감(실패) D=삭제';

--프로젝트 번호 시퀀스
DROP SEQUENCE SEQ_PROJECT_NO;
CREATE SEQUENCE SEQ_PROJECT_NO NOCACHE NOCYCLE;

---------------------------------------------------
--DESCRIPTION_FILE 프로젝트 상세페이지 첨부파일
---------------------------------------------------

DROP TABLE DESCRIPTION_FILE CASCADE CONSTRAINTS;

CREATE TABLE DESCRIPTION_FILE
(
    NO NUMBER PRIMARY KEY,
    PROJECT_NO NUMBER NOT NULL,
    FILE_SRC VARCHAR2(1000) NOT NULL,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255)NOT NULL,
    UPLOAD_DATE TIMESTAMP DEFAULT SYSDATE
);

--프로젝트 번호 외래키 지정 (파일)
ALTER TABLE DESCRIPTION_FILE ADD CONSTRAINT ATT_PROJECT_REF_NO 
FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT;

--첨부파일 번호 시퀀스
DROP SEQUENCE SEQ_DESCRIPTION_NO;
CREATE SEQUENCE SEQ_DESCRIPTION_NO NOCACHE NOCYCLE;