------------------------------------
--ADMIN
------------------------------------


--관리자 테이블 삭제
DROP TABLE ADMIN CASCADE CONSTRAINTS;

--관리자 테이블 생성
CREATE TABLE ADMIN (
    NO           NUMBER           PRIMARY KEY
    , ID         VARCHAR2(100)    NOT NULL    
    , PWD        VARCHAR2(100)    NOT NULL
    , NAME       VARCHAR2(15)     DEFAULT '관리자'
);

--시퀀스 삭제
DROP SEQUENCE SEQ_ADMIN_NO;

--시퀀스 생성
CREATE SEQUENCE SEQ_ADMIN_NO
NOCACHE NOCYCLE;

--관리자 더미데이터 생성
INSERT INTO ADMIN (NO,ID,PWD) VALUES (SEQ_ADMIN_NO.NEXTVAL, 'admin', '1234');

--커밋
COMMIT;





------------------------------------
--EVENT
------------------------------------

--이벤트 테이블 삭제
DROP TABLE EVENT CASCADE CONSTRAINTS;

--이벤트 테이블 생성
CREATE TABLE EVENT (
    NO                  NUMBER              PRIMARY KEY
    , ADMIN_NO           NUMBER              NOT NULL
    , TITLE             VARCHAR2(200)       NOT NULL
    , CONTENT           VARCHAR2(1000)      NOT NULL
    , THUMBNAIL_PATH    VARCHAR2(1000)      NOT NULL           
    , THUMBNAIL_NAME    VARCHAR2(255)       NOT NULL           
    , WRITE_DATE        TIMESTAMP           DEFAULT SYSDATE
    , START_DATE        DATE                NOT NULL
    , END_DATE          DATE                NOT NULL
    , IMPORTANT_YN      CHAR(1)             DEFAULT 'N' CHECK(IMPORTANT_YN IN('Y','N'))
    , EDIT_DATE         TIMESTAMP           DEFAULT SYSDATE
    , EDIT_ADMIN_NO     NUMBER              NULL
    , STATUS             CHAR(1)            DEFAULT 'B' CHECK(STATUS IN('B','I','E','D'))
)
;

--시퀀스 삭제
DROP SEQUENCE SEQ_EVENT_NO;

--시퀀스 생성
CREATE SEQUENCE SEQ_EVENT_NO
NOCACHE NOCYCLE;

--이벤트 더미데이터 생성
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트1' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트2' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트3' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트4' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트5' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트6' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트7' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트8' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트9' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트10' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트11' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트12' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트13' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트14' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;
INSERT INTO EVENT (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME,START_DATE,END_DATE)VALUES (SEQ_EVENT_NO.NEXTVAL , 1 , '이벤트15' , '이벤트내용' , '경로' , '이름' , '2022-08-01' , '2022-09-01' ) ;


--커밋
COMMIT;



------------------------------------
--EVENT_FILE
------------------------------------

--이벤트 파일 테이블 삭제
DROP TABLE EVENT_FILE CASCADE CONSTRAINTS;

--이벤트 파일 테이블 생성
CREATE TABLE EVENT_FILE (
    NO              NUMBER          PRIMARY KEY
    , EVENT_NO       NUMBER          NOT NULL
    , PATH          VARCHAR2(1000)  NOT NULL
    , NAME          VARCHAR2(255)   NOT NULL
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DELETE_YN     CHAR(1)         DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
)
;

--시퀀스 삭제
DROP SEQUENCE SEQ_EVENT_FILE_NO;

--시퀀스 생성
CREATE SEQUENCE SEQ_EVENT_FILE_NO
NOCACHE NOCYCLE;

--이벤트 파일 더미데이터 생성

--커밋
COMMIT;



------------------------------------
--NOTICE
------------------------------------

--공지사항 테이블 삭제
DROP TABLE NOTICE CASCADE CONSTRAINTS;

--공지사항 테이블 생성
CREATE TABLE NOTICE (
    NO                  NUMBER              PRIMARY KEY
    , ADMIN_NO          NUMBER              NOT NULL
    , TITLE             VARCHAR2(200)       NOT NULL
    , CONTENT           VARCHAR2(1000)      NOT NULL
    , THUMBNAIL_PATH    VARCHAR2(1000)      NOT NULL           
    , THUMBNAIL_NAME    VARCHAR2(255)       NOT NULL           
    , WRITE_DATE        TIMESTAMP           DEFAULT SYSDATE
    , IMPORTANT_YN      CHAR(1)             DEFAULT 'N' CHECK(IMPORTANT_YN IN('Y','N'))
    , EDIT_DATE         TIMESTAMP           DEFAULT SYSDATE
    , EDIT_ADMIN_NO     NUMBER              NULL
    , DELETE_YN         CHAR(1)             DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
)
;

--시퀀스 삭제
DROP SEQUENCE SEQ_NOTICE_NO;

--시퀀스 생성
CREATE SEQUENCE SEQ_NOTICE_NO
NOCACHE NOCYCLE;

--공지사항 더미데이터 생성
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항1' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항2' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항3' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항4' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항5' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항6' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항7' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항8' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항9' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항10' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항11' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항12' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항13' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항14' , '공지사항내용' , '경로' , '이름') ;
INSERT INTO NOTICE (NO,ADMIN_NO,TITLE,CONTENT,THUMBNAIL_PATH,THUMBNAIL_NAME)VALUES (SEQ_NOTICE_NO.NEXTVAL , 1 , '공지사항15' , '공지사항내용' , '경로' , '이름') ;

--커밋
COMMIT;




------------------------------------
--NOTCIE_FILE
------------------------------------

--공지사항 파일 테이블 삭제
DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;

--공지사항 파일 테이블 생성
CREATE TABLE NOTICE_FILE (
    NO              NUMBER          NOT NULL
    , NOTICE_NO       NUMBER          NOT NULL
    , PATH          VARCHAR2(1000)  NOT NULL
    , NAME          VARCHAR2(255)   NOT NULL
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DELETE_YN     CHAR(1)         DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
)
;

--시퀀스 삭제
DROP SEQUENCE SEQ_NOTICE_FILE_NO;

--시퀀스 생성
CREATE SEQUENCE SEQ_NOTICE_FILE_NO
NOCACHE NOCYCLE;

--공지사항 파일 더미데이터 생성



--커밋
COMMIT;


----------------------------------------------------------
----------------------------------------------------------
--외래키 설정
-----------------------------------------------------------

--이벤트 외래키
ALTER TABLE EVENT
ADD CONSTRAINT EVENT_ADMIN_REF_NO 
FOREIGN KEY (ADMIN_NO) REFERENCES ADMIN;

--공지사항 외래키
ALTER TABLE NOTICE
ADD CONSTRAINT NOTICE_ADMIN_REF_NO 
FOREIGN KEY (ADMIN_NO) REFERENCES ADMIN;

--이벤트_파일 외래키
ALTER TABLE EVENT_FILE
ADD CONSTRAINT EVENT_FILE_EVENT_REF_NO 
FOREIGN KEY (EVENT_NO) REFERENCES EVENT;

--공지사항_파일 외래키
ALTER TABLE NOTICE_FILE
ADD CONSTRAINT NOTICE_FILE_NOTICE_REF_NO 
FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE;

--커밋
COMMIT;