SELECT COUNT(PROJECT_NO) COUNT FROM PROJECT WHERE STATUS = 'B';

SELECT * FROM MEMBER;

SELECT * FROM PAYMENT_CREDIT_CARD;

SELECT * FROM DONATE_LIST;

SELECT * FROM PROJECT;

SELECT * FROM ADMIN;

SELECT * FROM 
( SELECT ROWNUM AS RNUM , T.* FROM 
(SELECT * FROM  DONATE_LIST d LEFT OUTER 
JOIN (SELECT p.NAME P_TITLE, r.NO REARD_NO FROM REWARD r LEFT OUTER JOIN PROJECT p ON r.PROJECT_NO = p.PROJECT_NO) j 
ON d.REWARD_NO = REWARD_NO WHERE d.MEMBER_NO=1) T )
WHERE RNUM BETWEEN 1 AND 10;

SELECT T.* FROM
(
SELECT ROWNUM RNUM, E.* 
FROM EVENT E
) T
WHERE RNUM BETWEEN 10 AND 30
;

INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,1,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,2,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,3,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,4,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,5,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,6,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,7,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,8,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,9,1,'L');
INSERT INTO PROJECT_LIKE(NO,MEMBER_NO,PROJECT_NO,STATUS)VALUES(SEQ_PROJECT_LIKE_NO.NEXTVAL,10,1,'L');
COMMIT;