---------------------------------------------------
--CATEGORY 카테고리
---------------------------------------------------

DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CATEGORY
(
    CATEGORY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);

--카테고리 번호 시퀀스
DROP SEQUENCE SEQ_CATEGORY_NO;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE;

--카테고리 번호 외래키 지정 (프로젝트)
ALTER TABLE "PROJECT" ADD CONSTRAINT PROJECT_CATEGORY_REF_NO 
FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY;

--카테고리 INSERT
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(1, '푸드');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(2, '홈, 리빙');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(3, '모빌리티');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(4, '테크, 가전');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(5, '패션, 잡화');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(6, '반려동물');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(7, '도서, 출판');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(8, '여행, 레저');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(9, '클래스');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(10, '뷰티');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(11, '스포츠');
INSERT INTO CATEGORY(CATEGORY_NO , NAME) VALUES(12, '식테크');

COMMIT;