---------------------------------------
--DONATE_LIST 후원내역 테이블
---------------------------------------
DROP TABLE DONATE_LIST CASCADE CONSTRAINTS;
CREATE TABLE DONATE_LIST
(
    NO                  NUMBER      PRIMARY KEY,
    REWARD_NO           NUMBER      NOT NULL,
    MEMBER_NO           NUMBER      NOT NULL,
    PAYMENT_METHOD_NO   NUMBER      NOT NULL,
    DELIVERY_ADDR_NO    NUMBER      NOT NULL,
    DONATE_DATE         TIMESTAMP   DEFAULT SYSDATE,
    AMOUNT              NUMBER      NOT NULL,
    QUANTITY            NUMBER      NOT NULL,
    ADDITIONAL          NUMBER      DEFAULT 0,
    CANCEL_YN           CHAR(1)     DEFAULT 'N' CHECK(CANCEL_YN IN('Y','N')),
    CANCEL_DATE         TIMESTAMP
);

--시퀀스
DROP SEQUENCE SEQ_DONATE_LIST_NO;
CREATE SEQUENCE SEQ_DONATE_LIST_NO NOCACHE NOCYCLE;

--제약조건
ALTER TABLE DONATE_LIST
ADD CONSTRAINT DONATE_LIST_REWARD_NO FOREIGN KEY(REWARD_NO) REFERENCES REWARD(NO);
ALTER TABLE DONATE_LIST
ADD CONSTRAINT DONATE_LIST_MEMBER_NO FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);
ALTER TABLE DONATE_LIST
ADD CONSTRAINT DONATE_LIST_PAYMENT_METHOD_NO FOREIGN KEY(PAYMENT_METHOD_NO) REFERENCES PAYMENT_CREDIT_CARD(NO);
ALTER TABLE DONATE_LIST
ADD CONSTRAINT DONATE_LIST_DELIVERY_ADDR_NO FOREIGN KEY(DELIVERY_ADDR_NO) REFERENCES DELIVERY_ADDRESS(NO);

--더미데이터
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,1,1,1,1,10000,1);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,1,2,1,1,24000,1);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,1,2385,1,1,50000,1);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,1,2386,1,1,73000,1);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY,ADDITIONAL)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,9,1,1,1,16000,2,2000);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY,ADDITIONAL)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,9,2,1,1,24000,1,2000);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY,ADDITIONAL)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,9,2385,1,1,84000,3,2000);
INSERT INTO DONATE_LIST(NO,REWARD_NO,MEMBER_NO,PAYMENT_METHOD_NO,DELIVERY_ADDR_NO,AMOUNT,QUANTITY,ADDITIONAL)
    VALUES(SEQ_DONATE_LIST_NO.NEXTVAL,9,2386,1,1,73000,2,2000);
COMMIT;




---------------------------
--TEST
---------------------------
SELECT * FROM DONATE_LIST;

INSERT INTO DONATE_LIST(
    NO
    ,REWARD_NO
    ,MEMBER_NO
    ,PAYMENT_METHOD_NO
    ,DELIVERY_ADDR_NO
    ,DONATE_DATE
    ,AMOUNT
    ,QUANTITY
    ,ADDITIONAL
)
VALUES
(
    SEQ_DONATE_LIST_NO.NEXTVAL
    ,?
    ,?
    ,?
    ,?
    ,?
    ,?
    ,?
    ,?
)
;