DROP TABLE PROJECT_LIKE CASCADE CONSTRAINTS;

CREATE TABLE PROJECT_LIKE(
    NO              NUMBER      PRIMARY KEY,
    MEMBER_NO       NUMBER,
    PROJECT_NO      NUMBER,
    STATUS          CHAR(1)     DEFAULT 'N' CHECK (STATUS IN ('L', 'N'))
);

ALTER TABLE PROJECT_LIKE
ADD CONSTRAINT LIKE_NO_MEMBER_NO FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);
ALTER TABLE PROJECT_LIKE
ADD CONSTRAINT LIKE_NO_PROJECT_NO FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO);

DROP SEQUENCE SEQ_PROJECT_LIKE_NO;
CREATE SEQUENCE SEQ_PROJECT_LIKE_NO NOCACHE NOCYCLE;