SELECT * FROM PROJECT;

UPDATE PROJECT SET STATUS = 'I'
WHERE STATUS = 'R'; 

COMMIT;

INSERT INTO PAYMENT_CREDIT_CARD(
    NO
    ,MEMBER_NO
    ,CARD_NUM
    ,VALID_DATE
    ,CARD_PWD
    ,BIRTH
    ,PASSWORD
    ,DEFAULT_YN
)
VALUES
(
    SEQ_PAYMENT_NO.NEXTVAL
    ,1
    ,'1111222233334444'
    ,'0326'
    ,'22'
    ,'20000101'
    ,123456
    ,'Y'
);


------------------------
--결제수단 테이블
------------------------

DROP TABLE PAYMENT_CREDIT_CARD CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_CREDIT_CARD(
    NO              NUMBER      PRIMARY KEY
    ,MEMBER_NO       NUMBER      NOT NULL
    ,CARD_NUM        CHAR(16)    NOT NULL
    ,VALID_DATE      CHAR(4)     NOT NULL
    ,CARD_PWD        CHAR(2)     NOT NULL
    ,BIRTH           CHAR(8)
    ,PASSWORD        NUMBER      NOT NULL
    ,REGISTRATION    CHAR(10)
    ,DEFAULT_YN      CHAR(1)     DEFAULT 'N' CHECK(DEFAULT_YN IN('N','Y'))
);

--결제수단 시퀀스
DROP SEQUENCE SEQ_PAYMENT_NO;
CREATE SEQUENCE SEQ_PAYMENT_NO NOCACHE NOCYCLE;

--회원번호 외래키
ALTER TABLE PAYMENT_CREDIT_CARD ADD CONSTRAINT PAYMENT_MEMBER_REF_NO 
FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);

--------------------------------
--DUMMY DATA
--------------------------------
INSERT INTO PAYMENT_CREDIT_CARD(
    NO
    ,MEMBER_NO
    ,CARD_NUM
    ,VALID_DATE
    ,CARD_PWD
    ,BIRTH
    ,PASSWORD
    ,DEFAULT_YN
)
VALUES
(
    SEQ_PAYMENT_NO.NEXTVAL
    ,1
    ,'1111222233334444'
    ,'0326'
    ,'22'
    ,'20000101'
    ,123456
    ,'Y'
);

INSERT INTO DELIVERY_ADDRESS(NO,MEMBER_NO,POST_NUM,ADDR1,ADDR2,NAME,PHONE,DEFAULT_YN)VALUES(SEQ_ADDR_NO.NEXTVAL,1,12345,'서울 강남구','테헤란로 1길 역삼역?','심원용','01012341234','Y');