DROP TABLE MY_MEMBER;
CREATE TABLE MY_MEMBER(
    NO          NUMBER          PRIMARY KEY
    ,ID         VARCHAR2(20)    NOT NULL
    ,PWD        VARCHAR2(100)   NOT NULL
    ,NAME       VARCHAR2(10)    NOT NULL
    ,TEL        CHAR(11)
    ,EMAIL      VARCHAR2(100)
    ,ADDR       VARCHAR2(300)
    ,GENDER     CHAR(1)         CHECK(GENDER IN('M','F'))
);

DROP SEQUENCE MY_MEMBER_SEQ;
CREATE SEQUENCE MY_MEMBER_SEQ NOCACHE NOCYCLE;

INSERT INTO MY_MEMBER(NO, ID, PWD, NAME, TEL, EMAIL, ADDR, GENDER)
VALUES(MY_MEMBER_SEQ.NEXTVAL, 'admin', '1234', 'ADMIN', '01012341234', '1111@NAVER.COM', '¼­¿ï', 'F');

SELECT *
FROM MY_MEMBER;

COMMIT;