-- SEMI DDL

--------------------------------
-- MEMBER
--------------------------------

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(30)    NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NAME          VARCHAR2(15)    NOT NULL
    , PHONE         CHAR(13)
    , EMAIL         VARCHAR2(100)
    , ADDR          VARCHAR2(100)
    , INTEREST      VARCHAR2(100)
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'N' CHECK(STATUS IN ('Y','N')) 
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

INSERT INTO MEMBER(NO, ID, PWD, NAME, PHONE, EMAIL, ADDR, INTEREST) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '관리자', '01012341234', 'abc@naver.com', '강남구 역삼동 테헤란로 1번길', '');

COMMIT;


--------------------------------
-- NOTICE
--------------------------------

DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER        NUMBER          NOT NULL
    , CNT           NUMBER          DEFAULT 0
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'N' CHECK(STATUS IN('Y','N'))
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO);

DROP SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE NOCYCLE;

INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항 111', '집보내줘', 1);
INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항 222', '집가고싶어', 1);
INSERT INTO NOTICE(NO, TITLE, CONTENT, WRITER) VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항 333', '흑흑', 1);

COMMIT;











-----TEST. 사용하고 지울 예정--------

SELECT 
    N.NO
    ,N.TITLE
    ,N.CONTENT
    ,M.NAME AS WRITER
    ,N.CNT
    ,N.ENROLL_DATE
    ,N.STATUS
FROM NOTICE N
JOIN MEMBER M ON N.WRITER = M.NO
WHERE N.STATUS = 'N'
AND N.NO = ?
;