--UNION : 칼럼 타입, 갯수 일치해야 함
--결과집합을 연결해줌(세로 형태로)

SELECT 10 AS 첫번째칼럼, 20 AS 두번째칼럼 FROM DUAL
UNION
SELECT 50 AS FIRSTCOL, 60 AS SECONDCOL FROM DUAL;

SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION
SELECT 999, '유재석' FROM DUAL;

--INTERSECT : 교집합 출력
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
INTERSECT
SELECT 7777, 'HUI' FROM DUAL;

--UNION ALL
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION ALL
SELECT 7777, 'HUI' FROM DUAL;

--MINUS : A 집합에서 B 집합과 교집합인 ROW를 뺌
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
MINUS
SELECT 7777, 'HUI' FROM DUAL;