--상품테이블, 카테고리테이블


DROP TABLE PRODUCT;
DROP TABLE CATEGORY;

----------------------------------------------------------
CREATE TABLE CATEGORY(
  CAT_NO NUMBER PRIMARY KEY check(CAT_NO between 1 and 6)
,"CATEGORY" VARCHAR2(50)NOT NULL
);

CREATE TABLE PRODUCT(
 PRD_NO NUMBER PRIMARY KEY
 ,CAT_NO NUMBER NOT NULL
 ,PRD_NAME VARCHAR2(100) NOT NULL
 ,"DESCRIPTION" VARCHAR2(100) NOT NULL
 ,PRICE NUMBER NOT NULL
 ,STOCK NUMBER DEFAULT 0
 ,
 CONSTRAINTS PRODUCT_FK FOREIGN KEY(CAT_NO) REFERENCES "CATEGORY"(CAT_NO)
);

INSERT INTO "CATEGORY" VALUES(
1, '개 사료'
);
INSERT INTO "CATEGORY" VALUES(
2, '고양이 사료'
);
INSERT INTO "CATEGORY" VALUES(
3, '개 간식'
);
INSERT INTO "CATEGORY" VALUES(
4, '고양이 간식'
);
INSERT INTO "CATEGORY" VALUES(
5, '장난감'
);
INSERT INTO "CATEGORY" VALUES(
6, '기타'
);
COMMIT;

--테스트용 상품

INSERT INTO PRODUCT VALUES(
101, 1, 'ANF 독 6','소고기,연어',17000,50
);
COMMIT;

--뷰

CREATE VIEW PRODUCT_CATEGORY AS SELECT P.CAT_NO, "CATEGORY", PRD_NO, PRD_NAME,
"DESCRIPTION", PRICE, STOCK
from PRODUCT P
join CATEGORY C
on p.cat_no = c.cat_no;

SELECT * FROM PRODUCT_CATEGORY;
SELECT * FROM PRODUCT;
SELECT * FROM "CATEGORY";