--∏Æ∫‰ ¿€º∫

CREATE TABLE REVIEW(
    NO NUMBER PRIMARY KEY
    , TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(4000)
    , WRITER_NO NUMBER 
    , REGISTER_DATE TIMESTAMP
    , DELETE_YN CHAR(1) CHECK(DELETE_YN IN ('Y','N'))
);

CREATE SEQUENCE REVIEW_NO_SEQ
NOCACHE
NOCYCLE
;

SELECT * FROM REVIEW;