DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    MEM_NO NUMBER PRIMARY KEY
    ,MEM_ID VARCHAR2(20) UNIQUE NOT NULL
    ,MEM_PWD VARCHAR2(20) NOT NULL
    ,NAME VARCHAR2(20) NOT NULL
    ,BIRTH DATE NOT NULL 
    ,PHONE CHAR(11) NOT NULL
    ,ADDRESS VARCHAR2(20) NOT NULL
    ,POINT NUMBER DEFAULT 0
    ,ENROLL_DATE DATE DEFAULT SYSDATE
    ,QUIT_YN CHAR(1) DEFAULT 'N' CHECK(QUIT_YN IN('Y', 'N'))
);
COMMIT;

--예제
INSERT INTO MEMBER(MEM_NO, MEM_ID, MEM_PWD, NAME, BIRTH, PHONE, ADDRESS)
VALUES(1, 'KIM', '1234', 'KIM', TO_DATE(951111), '01011112222', 'KH')
;  
INSERT INTO MEMBER(MEM_NO, MEM_ID, MEM_PWD, NAME, BIRTH, PHONE, ADDRESS)
VALUES(2, 'KIM02', '1234', 'LEE', TO_DATE(951112), '01011112222', 'LH')
;  
INSERT INTO MEMBER(MEM_NO, MEM_ID, MEM_PWD, NAME, BIRTH, PHONE, ADDRESS)
VALUES(3, 'KIM03', '1234', 'CHOI', TO_DATE(951113), '01011112222', 'CH')
;  



--시퀀스
DROP SEQUENCE MEMBER_NO_SEQ;
CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1 --증가하는 값 설정 (현재는 1)
START WITH 1 --시작값
MINVALUE 1 -- 최소값
MAXVALUE 999 --최대값
NOCYCLE --순환 여부 (CYCLE)
NOCACHE -- CACHE 100 -- 캐시여부  (사이즈)
;
COMMIT;

SELECT * FROM MEMBER;

SELECT ENROLL_DATE, QUIT_YN FROM MEMBER 
WHERE TO_CHAR(ENROLL_DATE)=TO_CHAR(SYSDATE);

SELECT SYSDATE FROM DUAL;