DROP TABLE ADOPT;

CREATE TABLE ADOPT(
    ADT_NO NUMBER PRIMARY KEY
    , ADM_ID VARCHAR2(100)
    , MEM_ID VARCHAR2(100) NOT NULL
    , TYPE CHAR(1)
    , ANI_NAME VARCHAR2(100) NOT NULL
    , ADOPT CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE ADOPT_SEQ
NOCACHE
NOCYCLE
;
INSERT INTO ADOPT(ADT_NO, ADM_ID, MEM_ID, TYPE, ANI_NAME, ADOPT) VALUES(ADOPT_SEQ.NEXTVAL, 'SHJ1', 'SHJ2', 'C', 'CHEESE', 'Y');
INSERT INTO ADOPT(ADT_NO, ADM_ID, MEM_ID, TYPE, ANI_NAME, ADOPT) VALUES(ADOPT_SEQ.NEXTVAL, 'SHJ3', 'SHJ4', 'D', 'DOGGY', 'N');
COMMIT;

SELECT * FROM ADOPT;