-- DML (SELECT), 연산자

-- 연산자 연습용 테이블 생성 (삭제 예정)
CREATE TABLE TEMP_TB(
      NAME VARCHAR2(100)
    , AGE NUMBER
);

INSERT INTO TEMP_TB(NAME, AGE) VALUES('4G', 26);
INSERT INTO TEMP_TB(NAME, AGE) VALUES('3A', 25);
INSERT INTO TEMP_TB(NAME, AGE) VALUES('2B', 20);
--COMMIT;

-- 조회
SELECT * FROM TEMP_TB;

-- 숫자 더하기 +
SELECT NAME 이름, AGE+1 내년나이 FROM TEMP_TB;


SELECT NAME, AGE, 1234 숫자추가 FROM TEMP_TB;
SELECT NAME, AGE, '9S' 나인즈 FROM TEMP_TB;
SELECT NAME, AGE, '9S' AS 내가만든칼럼 FROM TEMP_TB;
SELECT NAME, AGE, '9S' AS "내가 만든 칼럼" FROM TEMP_TB;
SELECT NAME, AGE, '9S' 내가만든칼럼 FROM TEMP_TB;
SELECT NAME, AGE, AGE 내가만든칼럼 FROM TEMP_TB;
SELECT NAME, AGE, AGE+3 마이칼럼 FROM TEMP_TB;

-- 문자열 더하기 ||
SELECT NAME, AGE FROM TEMP_TB;
SELECT NAME, AGE, NAME 내가만든칼럼 FROM TEMP_TB;
SELECT NAME, AGE, NAME+1 내가만든칼럼 FROM TEMP_TB; -- 실패
SELECT NAME, AGE, 1+1 내가만든칼럼 FROM TEMP_TB;
SELECT NAME, AGE, 1+'1' 내가만든칼럼 FROM TEMP_TB; -- 숫자+문자 => 숫자
SELECT NAME, AGE, 1||'1' 내가만든칼럼 FROM TEMP_TB; -- 숫자||문자 => 문자
SELECT NAME, AGE, 7 내가만든칼럼 FROM TEMP_TB; -- 숫자는 오른쪽 정렬
SELECT NAME, AGE, '7' 내가만든칼럼 FROM TEMP_TB; -- 문자는 왼쪽 정렬
SELECT NAME, AGE, NAME+'9S' 내가만든칼럼 FROM TEMP_TB; -- 실패
SELECT NAME, AGE, NAME||' YORHA' 내가만든칼럼 FROM TEMP_TB; -- 문자열 더하기 연산자
SELECT NAME, AGE, CONCAT(NAME,' YORHA') 내가만든칼럼 FROM TEMP_TB; -- CONCAT() 함수 사용

SELECT NAME||'('||AGE||')' "이름(나이)" FROM TEMP_TB; 

SELECT SYSDATE FROM TEMP_TB;

SELECT 123+1 FROM DUAL;

-- 연산자
/*
    = : 같다
    !=, ^=, <> : 같지 않다
    >, <, >=, <= : 대소 비교
    IS NULL : NULL 인지 확인
    IS NOT NULL : NULL이 아닌지 확인
    
    NOT : 부정연산자
    AND : 그리고(== 자바의 &&)
    OR : 또는(== 자바의 ||)
    BETWEEN A AND B : A와 B 사이 인지 확인
    IN, NOT IN : 포함 되는지 확인
    
    LIKE, NOT LIKE : 문자열 비교
    % : 0개 이상의 문자열
    _ : 한글자
*/

SELECT * FROM TEMP_TB;

SELECT NAME, AGE FROM TEMP_TB; -- 모든 행 출력

-- 나이가 20인 ROW만 출력
SELECT NAME, AGE 
FROM TEMP_TB 
WHERE AGE=20; 

-- 나이가 20이 아닌 ROW만 출력
SELECT NAME, AGE 
FROM TEMP_TB 
WHERE AGE!=20
--WHERE AGE^=20
--WHERE AGE<>20
;

-- 나이가 20 초과인 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE AGE>20
;

-- AGE가 NULL인 데이터 넣기
--INSERT INTO TEMP_TB(NAME, AGE) VALUES('9S', NULL);
INSERT INTO TEMP_TB(NAME) VALUES('9S');
--ROLLBACK;
SELECT * FROM TEMP_TB;
--COMMIT;

-- AGE 칼럼의 값이 NULL인 ROW만 출력
SELECT NAME, AGE
FROM TEMP_TB
--WHERE AGE IS NULL
WHERE AGE IS NOT NULL
;

-- AGE가 19 초과 이면서 21 이하는 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE AGE > 10
AND AGE <= 21
;

-- AGE가 20 이하 이거나, 22 이상인 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE AGE <= 20
OR AGE >= 22
;

-- AGE가 21~22 사이에 해당하는 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE AGE BETWEEN 25 AND 26
;

-- NAME 이 '4G' 또는 '3A' 또는 '2B' 또는 '9S' 인 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
--WHERE NAME IN('4G', '3A', '2B', '9S')
WHERE NAME NOT IN('2B', '9S')
;

-- 이름이 4로 시작하는 ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE NAME LIKE '%A%'
--WHERE NAME NOT LIKE '%A%'
;

--이름이 '김'으로 시작하는(3글자 이름을 가진) ROW 출력
SELECT NAME, AGE
FROM TEMP_TB
WHERE NAME LIKE '김__'
--WHERE NAME NOT LIKE '김__'
;



-- 데이터 넣기
INSERT INTO TEMP_TB(NAME) VALUES('EVE');
INSERT INTO TEMP_TB(NAME) VALUES('ADAM');
INSERT INTO TEMP_TB(NAME) VALUES('DU');
INSERT INTO TEMP_TB(NAME) VALUES('GRAHA');
INSERT INTO TEMP_TB(NAME) VALUES('HUI');
INSERT INTO TEMP_TB(NAME) VALUES('EMET');
INSERT INTO TEMP_TB(NAME) VALUES('홍길동');
INSERT INTO TEMP_TB(NAME) VALUES('홍수환');
INSERT INTO TEMP_TB(NAME) VALUES('장정구');
INSERT INTO TEMP_TB(NAME) VALUES('김철수');
INSERT INTO TEMP_TB(NAME) VALUES('김수한무거북이와두루미삼천갑자동방삭');
--COMMIT;

-- 연습용 테이블 삭제
-- DROP TABLE TEMP_TB;
