-- 집계

--GROUP BY
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY DEPTNO, JOB
;

--ROLLUP
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB)
;

--CUBE
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
;

--DELETE FROM EMP WHERE ENAME = 'HUI';
--COMMIT;

--GRUPING SETS
SELECT DEPTNO, JOB, SUM(SAL) 총급여
FROM EMP
GROUP BY GROUPING SETS(DEPTNO, JOB)
;

--소집계
--ROLLUP, CUBE, GROUPING SETS 3개 함수에 대해 보조
--GROUPING
SELECT 
    DEPTNO
    , CASE --GROUPING(DEPTNO) 널값인지판단
        WHEN GROUPING(DEPTNO)=1 THEN '부서번호제외통계'
        WHEN GROUPING(JOB)=1 THEN 'JOB제외통계'
        ELSE '엘스'
    END "통계에서 제외한 칼럼"
    , JOB
    , SUM(SAL) 총급여
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
;