--트리거

CREATE OR REPLACE TRIGGER TRG_BOARD --만들기 뿐만 아니라 덮어쓰기도 가능...
AFTER INSERT OR DELETE OR UPDATE ON BOARD --셋중 하나만 걸려라...
FOR EACH ROW --행마다 작업
    BEGIN
        IF INSERTING THEN
            INSERT INTO BOARD_COPY(TITLE, CONTENT) VALUES(:NEW.TITLE,:NEW.CONTENT);
        END IF;
        IF DELETING THEN
            INSERT INTO BOARD_TRASH(TITLE, CONTENT) VALUES(:OLD.TITLE,:OLD.CONTENT);
        END IF;
        IF UPDATING THEN
            INSERT INTO BOARD_LOG(TITLE, CONTENT) VALUES(:OLD.TITLE,:OLD.CONTENT || '=>' || :NEW.CONTENT);
        END IF;
END TRG_BOARD
;