--¼øÀ§

SELECT ROW_NUMBER() OVER(ORDER BY HIREDATE) AS RN, E.* 
FROM EMP E
;

SELECT RANK() OVER(ORDER BY HIREDATE) AS RN, E.* 
FROM EMP E
;

SELECT DENSE_RANK() OVER(ORDER BY HIREDATE) AS RN, E.* 
FROM EMP E
;

--±×·ì ³ª´²¼­ ·©Å·
SELECT RANK() OVER(PARTITION BY DEPTNO ORDER BY HIREDATE DESC) AS RN, E.* 
FROM EMP E
;